# yaml-language-server: $schema=https://github.com/rnbguy/pages/raw/main/config.schema.json
# paths (using defaults: src=src, dest=dist, port=8000)
url: "https://ranadeep.in"

# site
title: "Ranadeep Biswas"
description: "Personal Website"
lang: en
github: "rnbguy"
email: "mail@ranadeep.in"
image: ""
twitter:
  profile: "rnbguy_"

# branding
logo: "github"
faviconText: "R"

# seo
robots: "index, follow"

# content
mermaid:
  useAscii: true
  paddingX: 5
  paddingY: 5
  boxBorderPadding: 1

# navigation
navBar:
  - CV: /ranadeep_cv.pdf
